version: "3"
services:
  dcsl-app:
    image: dcsl-app
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  dcsl-api:
    image: dcsl-api
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge